import localFont from "next/font/local";
import {Work_Sans} from "next/font/google"
import { NavBar } from "@/components/NavBar";
import "./styles/globals.scss";

const work_sans = Work_Sans({
  subsets: ['latin'],
  variable:"--font-work-sans",
  weight: ['100','200','300','400','500','600','700','800','900']
});

//! find mansory font and set it in the project
// const mansory = localFont({
//   src:"./fonts/GeistVF.woff",
//   variable:"--font-mansory",
//   weight: ['100','200','300','400','500','600','700','800','900']
// });


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${work_sans.variable}`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
